import type { Region } from "./types";

export type Country = {
  code: string;
  name: string;
  region: Region;
};

export const WORLD: Country = {
  code: "WORLD",
  name: "World",
  region: "International",
};

export const COUNTRIES: Country[] = [
  WORLD,
  { code: "AF", name: "Afghanistan", region: "Asia" },
  { code: "AL", name: "Albania", region: "Europe" },
  { code: "DZ", name: "Algeria", region: "Africa" },
  { code: "AD", name: "Andorra", region: "Europe" },
  { code: "AO", name: "Angola", region: "Africa" },
  { code: "AR", name: "Argentina", region: "Americas" },
  { code: "AM", name: "Armenia", region: "Asia" },
  { code: "AU", name: "Australia", region: "Oceania" },
  { code: "AT", name: "Austria", region: "Europe" },
  { code: "AZ", name: "Azerbaijan", region: "Asia" },
  { code: "BS", name: "Bahamas", region: "Americas" },
  { code: "BH", name: "Bahrain", region: "Asia" },
  { code: "BD", name: "Bangladesh", region: "Asia" },
  { code: "BB", name: "Barbados", region: "Americas" },
  { code: "BY", name: "Belarus", region: "Europe" },
  { code: "BE", name: "Belgium", region: "Europe" },
  { code: "BZ", name: "Belize", region: "Americas" },
  { code: "BJ", name: "Benin", region: "Africa" },
  { code: "BT", name: "Bhutan", region: "Asia" },
  { code: "BO", name: "Bolivia", region: "Americas" },
  { code: "BA", name: "Bosnia and Herzegovina", region: "Europe" },
  { code: "BW", name: "Botswana", region: "Africa" },
  { code: "BR", name: "Brazil", region: "Americas" },
  { code: "BN", name: "Brunei", region: "Asia" },
  { code: "BG", name: "Bulgaria", region: "Europe" },
  { code: "BF", name: "Burkina Faso", region: "Africa" },
  { code: "BI", name: "Burundi", region: "Africa" },
  { code: "KH", name: "Cambodia", region: "Asia" },
  { code: "CM", name: "Cameroon", region: "Africa" },
  { code: "CA", name: "Canada", region: "Americas" },
  { code: "CV", name: "Cabo Verde", region: "Africa" },
  { code: "CF", name: "Central African Republic", region: "Africa" },
  { code: "TD", name: "Chad", region: "Africa" },
  { code: "CL", name: "Chile", region: "Americas" },
  { code: "CN", name: "China", region: "Asia" },
  { code: "CO", name: "Colombia", region: "Americas" },
  { code: "KM", name: "Comoros", region: "Africa" },
  { code: "CG", name: "Congo", region: "Africa" },
  { code: "CD", name: "Congo (DRC)", region: "Africa" },
  { code: "CR", name: "Costa Rica", region: "Americas" },
  { code: "CI", name: "Côte d'Ivoire", region: "Africa" },
  { code: "HR", name: "Croatia", region: "Europe" },
  { code: "CU", name: "Cuba", region: "Americas" },
  { code: "CY", name: "Cyprus", region: "Europe" },
  { code: "CZ", name: "Czechia", region: "Europe" },
  { code: "DK", name: "Denmark", region: "Europe" },
  { code: "DJ", name: "Djibouti", region: "Africa" },
  { code: "DO", name: "Dominican Republic", region: "Americas" },
  { code: "EC", name: "Ecuador", region: "Americas" },
  { code: "EG", name: "Egypt", region: "Africa" },
  { code: "SV", name: "El Salvador", region: "Americas" },
  { code: "GQ", name: "Equatorial Guinea", region: "Africa" },
  { code: "ER", name: "Eritrea", region: "Africa" },
  { code: "EE", name: "Estonia", region: "Europe" },
  { code: "SZ", name: "Eswatini", region: "Africa" },
  { code: "ET", name: "Ethiopia", region: "Africa" },
  { code: "FJ", name: "Fiji", region: "Oceania" },
  { code: "FI", name: "Finland", region: "Europe" },
  { code: "FR", name: "France", region: "Europe" },
  { code: "GA", name: "Gabon", region: "Africa" },
  { code: "GM", name: "Gambia", region: "Africa" },
  { code: "GE", name: "Georgia", region: "Asia" },
  { code: "DE", name: "Germany", region: "Europe" },
  { code: "GH", name: "Ghana", region: "Africa" },
  { code: "GR", name: "Greece", region: "Europe" },
  { code: "GT", name: "Guatemala", region: "Americas" },
  { code: "GN", name: "Guinea", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", region: "Africa" },
  { code: "GY", name: "Guyana", region: "Americas" },
  { code: "HT", name: "Haiti", region: "Americas" },
  { code: "HN", name: "Honduras", region: "Americas" },
  { code: "HK", name: "Hong Kong", region: "Asia" },
  { code: "HU", name: "Hungary", region: "Europe" },
  { code: "IS", name: "Iceland", region: "Europe" },
  { code: "IN", name: "India", region: "Asia" },
  { code: "ID", name: "Indonesia", region: "Asia" },
  { code: "IR", name: "Iran", region: "Asia" },
  { code: "IQ", name: "Iraq", region: "Asia" },
  { code: "IE", name: "Ireland", region: "Europe" },
  { code: "IL", name: "Israel", region: "Asia" },
  { code: "IT", name: "Italy", region: "Europe" },
  { code: "JM", name: "Jamaica", region: "Americas" },
  { code: "JP", name: "Japan", region: "Asia" },
  { code: "JO", name: "Jordan", region: "Asia" },
  { code: "KZ", name: "Kazakhstan", region: "Asia" },
  { code: "KE", name: "Kenya", region: "Africa" },
  { code: "KW", name: "Kuwait", region: "Asia" },
  { code: "KG", name: "Kyrgyzstan", region: "Asia" },
  { code: "LA", name: "Laos", region: "Asia" },
  { code: "LV", name: "Latvia", region: "Europe" },
  { code: "LB", name: "Lebanon", region: "Asia" },
  { code: "LS", name: "Lesotho", region: "Africa" },
  { code: "LR", name: "Liberia", region: "Africa" },
  { code: "LY", name: "Libya", region: "Africa" },
  { code: "LT", name: "Lithuania", region: "Europe" },
  { code: "LU", name: "Luxembourg", region: "Europe" },
  { code: "MG", name: "Madagascar", region: "Africa" },
  { code: "MW", name: "Malawi", region: "Africa" },
  { code: "MY", name: "Malaysia", region: "Asia" },
  { code: "MV", name: "Maldives", region: "Asia" },
  { code: "ML", name: "Mali", region: "Africa" },
  { code: "MT", name: "Malta", region: "Europe" },
  { code: "MR", name: "Mauritania", region: "Africa" },
  { code: "MU", name: "Mauritius", region: "Africa" },
  { code: "MX", name: "Mexico", region: "Americas" },
  { code: "MD", name: "Moldova", region: "Europe" },
  { code: "MN", name: "Mongolia", region: "Asia" },
  { code: "ME", name: "Montenegro", region: "Europe" },
  { code: "MA", name: "Morocco", region: "Africa" },
  { code: "MZ", name: "Mozambique", region: "Africa" },
  { code: "MM", name: "Myanmar", region: "Asia" },
  { code: "NA", name: "Namibia", region: "Africa" },
  { code: "NP", name: "Nepal", region: "Asia" },
  { code: "NL", name: "Netherlands", region: "Europe" },
  { code: "NZ", name: "New Zealand", region: "Oceania" },
  { code: "NI", name: "Nicaragua", region: "Americas" },
  { code: "NE", name: "Niger", region: "Africa" },
  { code: "NG", name: "Nigeria", region: "Africa" },
  { code: "KP", name: "North Korea", region: "Asia" },
  { code: "MK", name: "North Macedonia", region: "Europe" },
  { code: "NO", name: "Norway", region: "Europe" },
  { code: "OM", name: "Oman", region: "Asia" },
  { code: "PK", name: "Pakistan", region: "Asia" },
  { code: "PS", name: "Palestine", region: "Asia" },
  { code: "PA", name: "Panama", region: "Americas" },
  { code: "PG", name: "Papua New Guinea", region: "Oceania" },
  { code: "PY", name: "Paraguay", region: "Americas" },
  { code: "PE", name: "Peru", region: "Americas" },
  { code: "PH", name: "Philippines", region: "Asia" },
  { code: "PL", name: "Poland", region: "Europe" },
  { code: "PT", name: "Portugal", region: "Europe" },
  { code: "PR", name: "Puerto Rico", region: "Americas" },
  { code: "QA", name: "Qatar", region: "Asia" },
  { code: "RO", name: "Romania", region: "Europe" },
  { code: "RU", name: "Russia", region: "Europe" },
  { code: "RW", name: "Rwanda", region: "Africa" },
  { code: "SA", name: "Saudi Arabia", region: "Asia" },
  { code: "SN", name: "Senegal", region: "Africa" },
  { code: "RS", name: "Serbia", region: "Europe" },
  { code: "SL", name: "Sierra Leone", region: "Africa" },
  { code: "SG", name: "Singapore", region: "Asia" },
  { code: "SK", name: "Slovakia", region: "Europe" },
  { code: "SI", name: "Slovenia", region: "Europe" },
  { code: "SO", name: "Somalia", region: "Africa" },
  { code: "ZA", name: "South Africa", region: "Africa" },
  { code: "KR", name: "South Korea", region: "Asia" },
  { code: "SS", name: "South Sudan", region: "Africa" },
  { code: "ES", name: "Spain", region: "Europe" },
  { code: "LK", name: "Sri Lanka", region: "Asia" },
  { code: "SD", name: "Sudan", region: "Africa" },
  { code: "SR", name: "Suriname", region: "Americas" },
  { code: "SE", name: "Sweden", region: "Europe" },
  { code: "CH", name: "Switzerland", region: "Europe" },
  { code: "SY", name: "Syria", region: "Asia" },
  { code: "TW", name: "Taiwan", region: "Asia" },
  { code: "TJ", name: "Tajikistan", region: "Asia" },
  { code: "TZ", name: "Tanzania", region: "Africa" },
  { code: "TH", name: "Thailand", region: "Asia" },
  { code: "TL", name: "Timor-Leste", region: "Asia" },
  { code: "TG", name: "Togo", region: "Africa" },
  { code: "TT", name: "Trinidad and Tobago", region: "Americas" },
  { code: "TN", name: "Tunisia", region: "Africa" },
  { code: "TR", name: "Türkiye", region: "Asia" },
  { code: "TM", name: "Turkmenistan", region: "Asia" },
  { code: "UG", name: "Uganda", region: "Africa" },
  { code: "UA", name: "Ukraine", region: "Europe" },
  { code: "AE", name: "United Arab Emirates", region: "Asia" },
  { code: "GB", name: "United Kingdom", region: "Europe" },
  { code: "US", name: "United States", region: "Americas" },
  { code: "UY", name: "Uruguay", region: "Americas" },
  { code: "UZ", name: "Uzbekistan", region: "Asia" },
  { code: "VE", name: "Venezuela", region: "Americas" },
  { code: "VN", name: "Vietnam", region: "Asia" },
  { code: "YE", name: "Yemen", region: "Asia" },
  { code: "ZM", name: "Zambia", region: "Africa" },
  { code: "ZW", name: "Zimbabwe", region: "Africa" },
];

export function findCountry(code: string): Country {
  const upper = code.toUpperCase();
  return COUNTRIES.find((c) => c.code === upper) ?? WORLD;
}
